default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: readinglist
  password: listreading

development:
  <<: *default
  database: readinglist_development

test:
  <<: *default
  database: readinglist_test

